### ISSUE TITLE
`genmoji generate` doesn't print network errors, but `genmoji commit` does.

### ISSUE THREAD

**Issue by Aurailus** [segersniels/genmoji#5]
I'm sorta new to using CLI Tools with OpenAI, and so I had to generate a new OpenAI key to use this tool. I generated it for the wrong account, which didn't have usage limits set, and `genmoji generate` just kept failing silently. It would spin for a second, and then an empty string would be returned. When I tried using `genmoji commit` to see if I got anything different, I got an actual network error stating what I had done wrong:
```
❯ genmoji generate

❯ genmoji commit
2024/11/14 14:51:38 error, status code: 429, message: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
``` 
In my opinion, error strings should be outputted regardless of what command is invoked. I thought there was a bug in the tool for a little bit there, instead of it being user error. (As an aside, I got it working after fixing the API key. Thank you for the great tool!)

**Comment by segersniels** [comment]
Should be fixed now! Sorry for that. 
You should be able to update by running the one-liner again from https://github.com/segersniels/genmoji?tab=readme-ov-file#install.

Next versions should report when an update is available.
