### ISSUE TITLE
Feature request: Config option to also check unstaged files.

### ISSUE THREAD

**Issue by Aurailus** [segersniels/genmoji#6]
In VSCode, there's an option to commit all files if no changes are explicitly staged. I use this, which means that when I'm preparing to commit my code, usually nothing is staged. When I run `genmoji generate` in this state, I get a message which says `no staged changes found`. I know this workflow is unusual, so I don't think sending all changes should be the default option. But it would be nice if there was a config option that made it so that if no changes are staged, it sends all modified files. Just a suggestion though!

**Comment by segersniels** [comment]
Thanks for the suggestion, but not sure if that falls within the scope of `genmoji`. The idea of committing has always been -- stage your files and commit them. So in that sense generating commit messages before something has been staged feels inherently _wrong_ to me (might just be me though).

If you're already in your terminal to generate commit messages, why not just do something like:
```bash
$ git add . && genmoji commit
```

And if you want to save time, just create an alias to your liking.

**Comment by Aurailus** [comment]
Understandable! I think it's more common than you might assume when working with visual git clients, but I can definitely create an alias. It'll have to be a bit more complex than the snippet you provided because I'll basically have to stage all iff there's nothing staged, and then unstage all after iif it was staged by the command, which is why I was suggesting an option in the tool to just ignore staged status. But if it's out of scope, that's totally fair! I'll handle it on my end :)
